require: rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/Documentation:
  Enabled: false