require: rubocop-rails
require: rubocop-rspec
require: rubocop-performance

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - bin/bundle

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - bin/bundle

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Style/Documentation:
  Enabled: false